# Development settings
# auto: true
# server: true
url: http://localhost:4000
# /development

# Production settings
# url: http://loganleger.com
cdn: http://assets.loganleger.com
# /production

baseurl: /
markdown: redcarpet
pygments: true
future: false
permalink: /:title
exclude: [Gemfile, Gemfile.lock, components, component.json, README.md, jekyll.thor]

redcarpet:
  extensions: [with_toc_data, smart, autolink, fenced_code_blocks, superscript, tables]