auto: true
server: true
baseurl: /
url: http://localhost:4000
destination: ./public
markdown: redcarpet
pygments: true
future: false
permalink: /:title
exclude: [Gemfile, Gemfile.lock, components, component.json, README.md]

redcarpet:
  extensions: [with_toc_data, smart]