auto: true
server: true
baseurl: /
# url: /
destination: ./public
markdown: redcarpet
pygments: true
future: false
permalink: /:title
exclude: [Gemfile, Gemfile.lock, components, component.json, README.md, scss]